### PR TITLE
Fix #87 https://github.com/remotestorage/modules/issues/87

### LINKED ISSUE #87: documents.js : Deadlinks in documentation and comments
Links to the BaseClient documentation in the Documents documentation are dead.

### PR DESCRIPTION
**Pull request by taophp**
The issue #87 should be fixed when @skddc will generate the documentation from the new source.

### CODE REVIEW

**Comment by skddc** [comment]
Thanks!

For some reason it didn't remove the `remove` docs when I ran the doc generation after the merge. But then I realized that it's actually still correct, as that's exactly how you can remove documents still. :) So I didn't care about finding out why it's not removed yet.

By the way, here are some tips on writing good commit messages (from our main rs.js repo): https://github.com/remotestorage/remotestorage.js/blob/master/CONTRIBUTING.md#commit-messages

**Comment by taophp** [comment]
@skddc Thanks for the link. I'll try to write better commit messages in the future.

**Comment by skddc** [comment]
Merged to master locally.

**Comment by skddc** [comment]
You're welcome. Merged to master locally.

**Comment by skddc** [comment]
By the way, if you add the email address that you're using for your local Git config to GitHub, then it can link your name to your profile.

**Pull request closed without merging**
