### PR TITLE
Use ES6

### PR DESCRIPTION
**Pull request by skddc**
This PR introduces module imports via ES6 and a Grunt setup for watching/building all modules from `src` to `dist`. With this, we can also start using other ES6 syntax and features, not just the module building.

### CODE REVIEW

**Comment by skddc** [comment]
Hint: ignore files from the `dist` and `doc` dirs when reviewing the code changes.

**Comment by skddc** [comment]
Reviews greatly appreciated! :)

/cc @Ragnis @galfert @silverbucket @clochix @michielbdejong

**Comment by skddc** [comment]
Still waiting for reviews...

**Comment by silverbucket** [comment]
It's a lot to review for me right now, brain totally elsewhere (working on sockethub docs) but I say, since this is the modules repo and we're still trying to get a working baseline, just go with it. We can all learn and adapt/improve as we start to get hands-on with it.

**Comment by skddc** [comment]
It looks like much more than what it is. As I said

> Hint: ignore files from the dist and doc dirs when reviewing the code changes.

At least one person who says it looks halfway ok would still be great, even if I merge it then.

**Comment by silverbucket** [comment]
Yeah, I know, ignoring the dist and doc files, it seems reasonable but that's just from my cursory glance. This makes me happy:
`import md5sum from "./utils/md5sum";`

:)

**Comment by skddc** [comment]
Alright. :)

**Comment by skddc** [comment]
Merged locally.

Also fixed all the maintainer/author headers in docs. Most of them weren't formatted correctly.

**Pull request closed without merging**
